version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy  # Ждём, пока БД станет доступна
    ports:
      - "15614:15614"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_LIQUIBASE_ENABLED: "false"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

volumes:
  postgres_data:
